---
- name: reload nginx
  service: name=nginx enabled=yes state=reloaded

- name: restart uwsgi_emperor
  service: name=uwsgi_emperor enabled=yes state=restarted

# TODO find a way to give a parameter to this
#- name: Reload uwsgi master
#  command: touch {{ app_dir }}/.../uwsgi.ini
