---
- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name: restart uwsgi_emperor  # TODO we can also just touch files to restart apps individually
  service: name=uwsgi_emperor enabled=yes state=restarted
