---

- name: Symlink uwsgi config file
  file: src={{ app_dir }}/{{ item }}/configs/uwsgi.ini dest=/etc/uwsgi/vassals/{{ item }}.uwsgi.ini state=link
  with_items:
    - "{{ app_names }}"

- name: Symlink nginx config file
  file: src={{ app_dir }}/{{ item }}/configs/nginx.conf dest=/etc/nginx/sites-enabled/{{ item }}.nginx.conf state=link
  with_items:
    - "{{ app_names }}"
