- hosts: app-server
  sudo: true
  roles:
    - init
    - webapp
    - { role: deploy, tags: [ 'deploy' ] }

- hosts: database
  sudo: true
  roles:
    - init
    - {
        role: ANXS.postgresql,
        postgresql_version: '9.3',
        postgresql_databases: [{ name: 'django_async'}],
        postgresql_users: [{ name: 'toto', pass: 'toto', encrypted: 'no'}],
        postgresql_pg_hba_default: [
          { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: '{{ postgresql_default_auth_method }}', comment: '' },
          { type: local, database: all, user: all, address: '', method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' },
          { type: host, database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' },
          { type: host, database: all, user: all, address: '{{ ansible_default_ipv4.address }}/0', method: 'md5', comment: 'IPv4 local network connections:' },
          { type: host, database: all, user: all, address: '::1/128', method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }
        ],
        postgresql_listen_addresses: '*',
        tags: [ 'database' ]
      }

- hosts: python-dev
  sudo: true
  roles:
    - init
    - python-env

- hosts: build-server
  sudo: true
  roles:
    - init
    - buildbot


