---

- name: Install uwsgi
  pip: executable={{ python_dir }}/python{{ python_version }}/bin/pip name=uWSGI version=2.0.7

- name: Create uwsgi etc directory
  file: path=/etc/uwsgi/vassals owner=root group=root mode=0755 state=directory

- name: Create uwsgi log directory
  file: path=/var/log/uwsgi owner=webapp group=webapp mode=0765 state=directory

- name: Installs uwsgi emperor configuration file
  template: src=uwsgi_emperor.ini dest=/etc/uwsgi/uwsgi_emperor.ini owner=root group=root mode=0644

- name: Install uwsgi upstart configuration file
  template: src=upstart-uwsgi_emperor.conf dest=/etc/init/uwsgi_emperor.conf owner=root group=root mode=0644
  notify:
    - restart uwsgi_emperor

