---

- name: Install system packages
  sudo: yes
  apt: pkg={{ item.key }} state={{ item.value }}
  with_dict:
    make: latest
    libbz2-dev: latest
    libpq-dev: latest  # this is used by psycopg2
    libpcre3: latest
    libpcre3-dev: latest

- name: Create python directory
  sudo: yes
  file: path={{ python_dir }} owner=root group=root mode=0755 state=directory

- name: Get python
  shell: "wget {{ python_source }} && tar zxvf Python-{{ python_version }}.tgz && cd Python-{{ python_version }}"
  args:
    chdir: "{{ python_dir }}"
    creates: "{{ python_dir }}/Python-{{ python_version }}"

- name: Install python
  shell: "./configure --prefix={{ python_dir }}/python{{ python_version }} && make && make install"
  args:
    chdir: "{{ python_dir }}/Python-{{ python_version }}"
    creates: "{{ python_dir }}/python{{ python_version }}"

- name: Download pip installation script
  copy: src=get-pip.py dest={{ python_dir }}

- name: Install pip
  command: "{{ python_dir }}/python{{ python_version }}/bin/python get-pip.py"
  args:
    chdir: "{{ python_dir }}"
    creates: "{{ python_dir }}/python{{ python_version }}/bin/pip"

- name: Install virtualenv
  pip: executable={{ python_dir }}/python{{ python_version }}/bin/pip name=virtualenv version=1.11.6

- name: Create app directory
  sudo: yes
  file: path={{ app_dir }} owner=root group=root mode=0755 state=directory

- name: Create app virtualenv directory
  sudo: yes
  file: path={{ venv_dir }} owner=root group=root mode=0755 state=directory
