---

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - libpq-dev  # this is used by psycopg2
    - libpcre3
    - libpcre3-dev

- name: Create app directory
  sudo: yes
  file: path={{ app_dir }} owner=root group=root mode=0755 state=directory

- name: Create app virtualenv directory
  sudo: yes
  file: path={{ venv_dir }} owner=root group=root mode=0755 state=directory

- name: Create virtualenvs for apps
  pip:
    virtualenv_command: "{{ python_dir }}/python{{ python_version }}/bin/virtualenv"
    virtualenv_site_packages: no
    virtualenv: "{{ venv_dir }}/{{ item }}"
    requirements: "{{ app_dir }}/{{ item }}/{{ python_requirements }}"
  with_items:
    - "{{ app_names }}"
