---

- name: Install system packages
  sudo: yes
  apt: pkg={{ item.key }} state={{ item.value }}
  with_dict:
    sqlite3: latest
    libsqlite3-dev: latest
    git: latest

- name: Create buildbot virtualenv
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    virtualenv_command: "{{ python_dir }}/python{{ python_version }}/bin/virtualenv"
    virtualenv_site_packages: no
    virtualenv: "{{ venv_dir }}/buildbot"
  with_dict:
    Jinja2: 2.7.3
    MarkupSafe: 0.23
    SQLAlchemy: 0.7.10
    Tempita: 0.5.2
    Twisted: 14.0.1
    buildbot: 0.8.9
    buildbot-slave: 0.8.9
    decorator: 3.4.0
    pysqlite: 2.6.3
    python-dateutil: 1.5
    sqlalchemy-migrate: 0.7.2
    wsgiref: 0.1.2
    zope.interface: 4.1.1

- include: master.yml
- include: slave.yml
