---
- name: Update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
    - acl
